//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Cash_Machine.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class Cash_x0020_machine_x0020_modelContainer : DbContext
    {
        public Cash_x0020_machine_x0020_modelContainer()
            : base("name=Cash_x0020_machine_x0020_modelContainer")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Card> CardSet { get; set; }
        public virtual DbSet<CardOperation> CardOperationSet { get; set; }
        public virtual DbSet<OperationType> OperationTypeSet { get; set; }
    }
}
